### ISSUE TITLE
Move from webpack to vite?

### ISSUE THREAD

**Issue by rafed** [Kocal/vue-web-extension-vue3#1]
I was just wondering if this could be moved from webpack to **vite**? Would provide a faster developer experience. Would greatly appreciate if done.

**Comment by Kocal** [comment]
Since this repository is only an example of migration from Vue 2 to Vue 3 for https://github.com/Kocal/vue-web-extension/issues/621, andvue-web-extension is Vue CLI preset (which use Webpack), I think it never gonna happens.
